INSERT INTO genres(genre_name, genre_logo) VALUES('Action', 'https://media.rawg.io/media/games/b7b/b7b8381707152afc7d91f5d95de70e39.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Indie', 'https://media.rawg.io/media/games/0be/0bea0a08a4d954337305391b778a7f37.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Adventure', 'https://media.rawg.io/media/games/4cb/4cb855e8ef1578415a928e53c9f51867.png') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('RPG', 'https://media.rawg.io/media/games/d0f/d0f91fe1d92332147e5db74e207cfc7a.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Shooter', 'https://media.rawg.io/media/games/73e/73eecb8909e0c39fb246f457b5d6cbbe.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Strategy', 'https://media.rawg.io/media/games/f95/f95ec06eddda5c5bf206618c49cd3e68.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Casual', 'https://media.rawg.io/media/screenshots/dc2/dc2814dc50d61be1ea4fcd5d3c03ddb6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Simulation', 'https://media.rawg.io/media/games/b4e/b4e4c73d5aa4ec66bbf75375c4847a2b.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Arcade', 'https://media.rawg.io/media/screenshots/6fe/6fe228662a253cd929cc78a103541ee0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Puzzle', 'https://media.rawg.io/media/screenshots/42d/42d770eb49f2ba01cd4045e0d92af7a9.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Platformer', 'https://media.rawg.io/media/games/4cf/4cfc6b7f1850590a4634b08bfab308ab.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Racing', 'https://media.rawg.io/media/games/9e5/9e52a797f049e701d4eee84774a99007.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Sports', 'https://media.rawg.io/media/games/cc5/cc576aa274780702ef93463f5410031e.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('MMO', 'https://media.rawg.io/media/screenshots/266/26605ea274a4dcada95f3f02b30fc2ed.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Family', 'https://media.rawg.io/media/screenshots/904/904809185a905c430f6c36f0ebf5353c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Fighting', 'https://media.rawg.io/media/screenshots/3e2/3e22f928180309b9f624628e71fdc447.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Board Games', 'https://media.rawg.io/media/screenshots/c25/c252e2023355e98787402c4bdd90f775.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Educational', 'https://media.rawg.io/media/screenshots/b10/b1037cefbbf94070dd4fae7ffbbd6999.jpg') ON CONFLICT DO NOTHING;
INSERT INTO genres(genre_name, genre_logo) VALUES('Card', 'https://media.rawg.io/media/screenshots/3e7/3e728c858ebd673e099cab3558a47d42.jpg') ON CONFLICT DO NOTHING;

INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PC', 'PC', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Windows_logo_-_2012.svg/1024px-Windows_logo_-_2012.svg.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation 4', 'PS4', 'https://i.ytimg.com/vi/56NxUWEFpL0/maxresdefault.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Xbox One', 'XBONE', 'http://4.bp.blogspot.com/-UcjPVSovGlk/UZvWPYBtgGI/AAAAAAAAVmc/8dJQeuz796I/s1600/xbox+one+logo.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('iOS', 'iOS', 'https://media.rawg.io/media/games/d5a/d5a24f9f71315427fa6e966fdd98dfa6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Android', 'ANDR', 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('macOS', 'Mac', 'https://media.rawg.io/media/games/e04/e04963f3ac4c4fa83a1dc0b9231e50db.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Linux', 'Linux', 'https://media.rawg.io/media/games/b8c/b8c243eaa0fbac8115e0cdccac3f91dc.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Nintendo Switch', 'NS', 'https://upload.wikimedia.org/wikipedia/commons/0/04/Nintendo_Switch_logo%2C_square.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Nintendo 3DS', '3DS', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Nintendo_3ds_logo.svg/2171px-Nintendo_3ds_logo.svg.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Nintendo DS', 'NDS', 'https://media.rawg.io/media/screenshots/4f2/4f2246a85225b7a91d63990fe540b7c4.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Nintendo DSi', 'DSi', 'https://media.rawg.io/media/screenshots/d08/d08c7c3e61d370afe9c8c741c36c51aa.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Xbox 360', 'X360', 'https://upload.wikimedia.org/wikipedia/it/thumb/c/c8/Xbox_360_-_Logo.svg/1200px-Xbox_360_-_Logo.svg.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Xbox', 'XBOX', 'https://media.rawg.io/media/games/400/400c2cc640653cd55a64f84f62602e26.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation 3', 'PS3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/PlayStation_3_Logo.svg/1280px-PlayStation_3_Logo.svg.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation 2', 'PS2', 'https://media.rawg.io/media/screenshots/4d6/4d6f9ef9a6e6ffd68392d18859fac2f8.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation', 'PS1', 'https://media.rawg.io/media/screenshots/19c/19ca7f49ab8f11e213de811f260f6786.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation Vita', 'PSVITA', 'http://www.jp.square-enix.com/dc_vita/en/images/main_logo_vita.png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('PlayStation Portable', 'PSP', 'https://media.rawg.io/media/games/c32/c32fd6c512c48b3e2f10686a6e06690d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Wii U', 'Wii U', 'http://img4.wikia.nocookie.net/__cb20121024163701/mario/images/d/dc/Wii_U_(Logo).png') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Wii', 'Wii', 'https://media.rawg.io/media/games/e6b/e6b025951f9a72673f41c0588fb85758.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('GameCube', 'GCN', 'https://media.rawg.io/media/screenshots/e31/e314b4861e9e6f095ca04a4b636e758c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Nintendo 64', 'N64', 'https://media.rawg.io/media/screenshots/e4c/e4c9fe1fb9c4f99d87cc641465f4ec99.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Game Boy Advance', 'GBA', 'https://media.rawg.io/media/games/02d/02da3c4a7c5cd335a9d45e24cdf1df6f.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Game Boy Color', 'GBC', 'https://media.rawg.io/media/screenshots/6df/6df71f3ff0f6d6bbac306cb9adf935ee.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Game Boy', 'GB', 'https://media.rawg.io/media/screenshots/f96/f96e2f756b3aa3e386e0b9f58c7c10c5.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('SNES', 'SNES', 'https://media.rawg.io/media/games/fc9/fc9bb16db9714d3731823fb0bf706533.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('NES', 'NES', 'https://media.rawg.io/media/games/e40/e4043e92866d08ec9fdd212dcd3a1224.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Classic Macintosh', 'CMac', 'https://media.rawg.io/media/games/dd7/dd72d8a527cd9245c7eb7cd05aa53efa.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Apple II', 'ApII', 'https://media.rawg.io/media/games/23e/23eecccb588a4a9c97f35ebf8f9f00ef.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Commodore / Amiga', 'C64', 'https://media.rawg.io/media/screenshots/79a/79ab3ca882e351d5423499723bc1890c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari 7800', '7800', 'https://media.rawg.io/media/screenshots/47e/47eeb8bb4e627c784a4904bbb9a739e0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari 5200', '5200', 'https://media.rawg.io/media/screenshots/5fa/5faaa4749ac1d65d7b5dff9a47d48dff.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari 2600', '2600', 'https://media.rawg.io/media/screenshots/b0e/b0e684fd240c803234cb9cdd8cb0e74e.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari Flashback', 'AtariF', 'https://media.rawg.io/media/screenshots/6ff/6ff0d1acf667e782d709d6fb96cddd0a.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari 8-bit', 'Atari8', 'https://media.rawg.io/media/games/054/0540c8fc8eed3fc13d3990f419c61c6f.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari ST', 'AtariS', 'https://media.rawg.io/media/screenshots/79a/79ab3ca882e351d5423499723bc1890c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari Lynx', 'Linx', 'https://media.rawg.io/media/screenshots/fe2/fe255f7d388075ccbdccb689ca218667.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Atari XEGS', 'Xegs', 'https://media.rawg.io/media/screenshots/769/7691726d70c23c029903df08858df001.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Genesis', 'GEN', 'https://media.rawg.io/media/screenshots/8ec/8ec4602c7f3e9f3a1ee51dd8582a7b78.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('SEGA Saturn', 'SAT', 'https://media.rawg.io/media/screenshots/862/862f0a3da04a5e2d5146b35e75e0d85b.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('SEGA CD', 'SEGACD', 'https://media.rawg.io/media/games/a9a/a9a2472f862b041d2980103ddbb61c91.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('SEGA 32X', '32X', 'https://media.rawg.io/media/screenshots/e3a/e3a8a714cb0f1a99451defd723a81ab6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('SEGA Master System', 'SMS', 'https://media.rawg.io/media/screenshots/f9a/f9ac59bb4af2ca2193ee9ffb979577cf.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Dreamcast', 'DC', 'https://media.rawg.io/media/games/96a/96a48ac7487d9db9179d83170afcb16a.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('3DO', '3DO', 'https://media.rawg.io/media/games/e41/e418a9f0a75697974d5e300bb20667ad.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Jaguar', 'Jaguar', 'https://media.rawg.io/media/screenshots/47c/47c0e7b847d36812735e75a0fd48dca9.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Game Gear', 'GG', 'https://media.rawg.io/media/games/e48/e4852b9be5eb6859870288d91f74aab6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Neo Geo', 'NEOGEO', 'https://media.rawg.io/media/screenshots/9be/9be442dd1deb0839f86ce7ec4be90787.jpg') ON CONFLICT DO NOTHING;
INSERT INTO platforms(platform_name, platform_name_short, platform_logo) VALUES('Web', 'Web', 'https://media.rawg.io/media/screenshots/2f2/2f2bca9ccd1d666e14f9f0554c42fb80.jpg') ON CONFLICT DO NOTHING;

INSERT INTO regions(region_name, region_short) VALUES('Worldwide', 'WW') ON CONFLICT DO NOTHING;

-- Game 1
INSERT INTO games(title, cover, description) VALUES('The Legend of Zelda: Breath of the Wild', 'https://media.rawg.io/media/games/cc1/cc196a5ad763955d6532cdba236f730c.jpg', 'The Legend of Zelda: Breath of the Wild is an adventure game developed by Nintendo. It is the nineteenth installment in the series. After awakening from a hundred year sleep, memoryless Link hears a mysterious female voice that guides him to a destroyed kingdom of Hyrule. He finds a Wiseman who says that a ruthless creature, Calamity Ganon, was imprisoned for 100 years. Even though the creature is trapped, it is still gaining power. Link sets out to kill Ganon before he frees himself and destroys the world. In contrast to the previous titles in the series, Breath of the Wild the player to explore a vast open world. At the beginning of the game, a small tutorial is given to the players and they are free to travel the world at the pace they see fit. Link can climb almost every surface in the world, search for new equipment, cook food to restore health. Fast travel to certain places in the world is also available for the players. The world is highly interactive. For example, trees can be chopped down in order to make fire, or Link can use his shield as a snowboard.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-03-02' FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/d8b/d8bfed2209bf96866506cca8022db5b7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Wii U') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Adventure') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'The Legend of Zelda: Breath of the Wild') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 2
INSERT INTO games(title, cover, description) VALUES('Super Bomberman R', 'https://media.rawg.io/media/screenshots/9d0/9d0c899bcf9c32aa64917a995a3b8d08.jpg', '') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-03-03' FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Konami', 'https://media.rawg.io/media/screenshots/31f/31fb3469ed4d19d55cf1906b5d54e0f8.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Konami') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Konami Digital Entertainment-US', 'https://media.rawg.io/media/screenshots/899/8999aa5111a7d2fd8d42389991737720.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Konami Digital Entertainment-US') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Konami Digital Entertainment', 'https://media.rawg.io/media/games/656/65637b0e1920bcb6664548de649bbe78.png') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Konami Digital Entertainment') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Arcade') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Bomberman R') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 3
INSERT INTO games(title, cover, description) VALUES('Snipperclips - Cut it out, together!', 'https://media.rawg.io/media/screenshots/706/7068196eb5089a05caecc45e5bdd36e5.jpg', 'Hey, cut it out! No, really! In this action-puzzle game, paper pals Snip and Clip must cut each other up to overcome tricky obstacles…or just to laugh their heads off (sometimes literally). Partner up with friends or family to cut the heroes into the right shapes, interact with objects, and solve a world of imaginative puzzles. Someone grab a paper weight—these puzzles just won''t stay still! The only limitation to solve puzzles is your imagination. Snip may need to cut Clip into a needle to pop balloons, or maybe they''ll have to team up to form a squawking, egg-laying bird! When playing together, prove you''re a cut above the rest in Blitz mode, where 2-4 players* can compete in a series of puzzlingly action-packed challenges. Three is never a crowd when you''re paper thin, so make it a party! In Party mode, up to four players* can team up to solve tough challenges. Ready or not, this couch co-op is a riot, any way you cut it!') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-03-03' FROM (SELECT game FROM games WHERE title LIKE 'Snipperclips - Cut it out, together!') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Snipperclips - Cut it out, together!') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('SFB Games', 'https://media.rawg.io/media/screenshots/284/28482cce144825eb04b0063fbcea1e39.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Snipperclips - Cut it out, together!') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'SFB Games') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Snipperclips - Cut it out, together!') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;

-- Game 4
INSERT INTO games(title, cover, description) VALUES('1-2-Switch', 'https://media.rawg.io/media/screenshots/57f/57f52ac1794c3f290f630b939e1f2709.jpg', 'Throw an impromptu party anywhere with anyone thanks to a new play style in which players look at each other—not the screen! Bring the action and fun into the real world as you face off in wild-west duels, cow-milking competitions, a copycat dance-off, and more. Each game takes advantage of the Joy-Con controller features of the Nintendo Switch system in different ways. While the action unfolds off- screen, the audience watches the players themselves instead of the screen. That makes it as hilarious to watch as it is to play – an instant party amplifier! Features: Face-to-Face Play – Look at your friends rather than the screen as you compete in a new style of video game party full of fast and fun face-to-face games. Stare down your opponent in a wild-west duel, mimic your opponent''s poses in a copycat dance-off, or rally for victory in a heated table tennis face-off. Anywhere with anyone – Bring fun and surprise to barbecues, house parties, or wherever you travel by using the built-in stand of the Nintendo Switch system. The Nintendo Switch system comes bundled with a pair of Joy-Con controllers, allowing the party to start with just one system and the game for instant multiplayer fun. Intuitive and simple controls using Joy-Con features – Simple rules make it easy for anyone to play and fun for everyone to watch. Each player holds a single Joy-Con, and different games use different controller features, such as motion control, HD rumble, or the IR Motion Camera.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-03-03' FROM (SELECT game FROM games WHERE title LIKE '1-2-Switch') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE '1-2-Switch') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/d8b/d8bfed2209bf96866506cca8022db5b7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE '1-2-Switch') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE '1-2-Switch') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;

-- Game 5
INSERT INTO games(title, cover, description) VALUES('Super Smash Bros. Ultimate', 'https://media.rawg.io/media/games/9f3/9f3c513b301d8d7250a64dd7e73c62df.jpg', 'Super Smash Bros. Ultimate is the fifth game in its franchise. It is also the first game in its series to be released for Nintendo Switch. The series is a crossover of characters from various video game franchises, such as The Legend of Zelda, Pokemon, Sonic the Hedgehog, Super Mario, Metroid, and Mega Man, among many others. Their famous protagonists fight each other on an arena. In accordance with its name, the game is the ''ultimate'' installment of the series, in that it offers the players all the characters ever featured in Super Smash Bros. The game also introduces five new characters, most famously, Castlevania''s Simon Belmont. Unlike most fighting games, Super Smash Bros. series is built around knocking opponents out of the arena rather than lowering their health bars. However, the damage meter increases the character''s chances to be knocked out. Each fighter has a limited number of lives and loses one when he or she is knocked out. The player is eliminated when he or she loses all lives. Super Smash Bros. Ultimate includes several competitive multiplayer modes. Besides the traditional versus mode, there are several new modes not featured in the previous games. These include Tournament (the playoff mode for 32 players), Smash Squad (team multiplayer), Smashdown (a mode in which the defeated characters are eliminated).') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2018-12-07' FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/d8b/d8bfed2209bf96866506cca8022db5b7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Bandai Namco Entertainment', 'https://media.rawg.io/media/screenshots/7a6/7a6727469c2a24cc4230effc3d280c3b.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Bandai Namco Entertainment') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Sora Ltd.', 'https://media.rawg.io/media/screenshots/aa4/aa4ce0d45cb2cc7e4309d9ffa5287c50.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Sora Ltd.') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Smash Bros. Ultimate') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Fighting') AS b ON CONFLICT DO NOTHING;

-- Game 6
INSERT INTO games(title, cover, description) VALUES('Katamari Damacy REROLL', 'https://media.rawg.io/media/games/842/8420626eee4e070554b7c975fbd27883.jpg', 'When the King of All Cosmos accidentally destroys all the stars in the sky, he orders you, his pint-sized princely son, to put the twinkle back in the heavens above. Join the King and Prince of Cosmos on their wacky adventure to restore the stars at home or on the go – now in full HD!') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2018-12-06' FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Bandai Namco Entertainment', 'https://media.rawg.io/media/games/8a0/8a02f84a5916ede2f923b88d5f8217ba.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Bandai Namco Entertainment') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('BANDAI NAMCO Entertainment US', 'https://media.rawg.io/media/screenshots/e7b/e7bca62abdf2ffdd794a0939a503c6b3.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'BANDAI NAMCO Entertainment US') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Monkeycraft', 'https://media.rawg.io/media/games/842/8420626eee4e070554b7c975fbd27883.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Monkeycraft') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('MONKEYCRAFT Co. Ltd.', 'https://media.rawg.io/media/games/842/8420626eee4e070554b7c975fbd27883.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'MONKEYCRAFT Co. Ltd.') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Casual') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Katamari Damacy REROLL') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Puzzle') AS b ON CONFLICT DO NOTHING;

-- Game 7
INSERT INTO games(title, cover, description) VALUES('Killer Queen Black', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg', 'Killer Queen Black, a new take on the arcade eSport Killer Queen, has been rebuilt from the ground up and optimized for PC. The gameplay is immediately recognizable and familiar, yet it introduces exciting new twists and online play! Fast, reactive, intense online multiplayer action for up to eight players. 6 maps. 5 distinct weapons: Sword, Morning Star, Laser, Lance, and Stinger. 4 game modes: Quick Match, Ranked, Custom, and Arena. 3 ways to win: Economic, Military, or Snail. 2 teams of 4 players each. 1 Black team Three Ways to WinIn Killer Queen Black, a team can win a game in three different ways. Economic victory: fill your base with berries * Military victory: kill the enemy Queen three times. Snail victory: ride her home! Online Play!Square off with 2 teams of up to 4 players each! Fly solo, or team up with three of your friends. 4 player couch online co-op. Single player or team based online play') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2018-12-01' FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('LLC', 'https://media.rawg.io/media/screenshots/9fe/9fe5e6d78e0371cfc1e006f7754dffea.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'LLC') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Liquid Bit. LLC', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Liquid Bit. LLC') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Liquid Bit', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Liquid Bit') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Liquid Bit, LLC', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Liquid Bit, LLC') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('BumbleBear', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'BumbleBear') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Liquid Bit', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Liquid Bit') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Liquid Bit, LLC', 'https://media.rawg.io/media/screenshots/741/741860e43c148d0798a0f208aec88aa0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Liquid Bit, LLC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'macOS') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Casual') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Strategy') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Sports') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Killer Queen Black') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Indie') AS b ON CONFLICT DO NOTHING;

-- Game 8
INSERT INTO games(title, cover, description) VALUES('Wolfenstein 2: The New Colossus', 'https://media.rawg.io/media/games/a0e/a0ef08621301a1eab5e04fa5c96978fa.jpeg', 'Wolfenstein 2: The New Colossus is a singleplayer FPS developed by MachineGames. It is the third installment in the rebooted series. Set in the alternate 1961 where Nazi Germany won World War II, the game picks up right at the end of Wolfenstein: The New Order. After sustaining heavy injuries in the battle with Wilhelm "Deathshead" Strasse, BJ Blaskowicz orders a nuclear strike on Deathshead''s compound in order to cripple the Nazi war machine, but he is evacuated by his comrades before the rocket launch. Blaskowicz falls unconscious for 5 months and is woken up by a Nazi attack. The player has to repel the attack and end the Nazi reign over America once and for all. The New Colossus features several stealth-action elements, just like the previous title in the series. There are some major differences in the mechanics: now BJ can modify his weaponry on-the-go, dual wield two different weapons at the same time. The cover system makes a comeback. The Protagonist doesn''t stick to cover, leaning out of it instead. The game offers a linear storyline, but the player is free to complete side-missions in any order they like. Completing these missions is rewarded with new weapon upgrades.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-10-27' FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/c4b/c4b0cab189e73432de3a250d8cf1c84e.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/55c/55c7e7a972d361db3677c1dd10a5558d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Machine Games', 'https://media.rawg.io/media/games/c64/c64d2f63cabeab9126693b7d39539c8d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Machine Games') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Shooter') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein 2: The New Colossus') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 9
INSERT INTO games(title, cover, description) VALUES('Super Mario Odyssey', 'https://media.rawg.io/media/games/267/267bd0dbc496f52692487d07d014c061.jpg', 'Super Mario Odyssey is a 3D platform game, a part of Nintendo''s Super Mario series. The game follows Mario on his quest to save Princess Peach from her forced marriage with Bowser. The game starts with Mario fighting Bowser on its aircraft. Bowers knock Mario off the ship and shreds his cap into pieces. Mario awakens in the Cap Kingdom inhabited with hat-like spirits and befriends one of them named Cappy. It turns out, Bowser also kidnapped Cappy’s sister Tiara, and now the heroes must chase Bowser through several kingdoms to save Peach and Tiara. The gameplay of Super Mario Odyssey draws inspiration from Super Mario 64 and Super Mario Sunshine. The game consists 17 levels (named as ''kingdoms''). In most of them, your goal is to collect a certain amount of Power Moons. Collecting enough of them allows the player to progress to the next kingdom. Some moons can be found in different parts of the level or acquired as a reward for completing certain tasks or challenges. The Mario’s moveset mostly resembles that of Super Mario 64 and includes wall jumps, triple jumps, somersaults, long jumps, rolling on the ground. The main new gameplay feature is that Mario can throw his hat to create temporary platforms, grab objects, attack enemies, or possess them. Possessing enemies gives you new moves and sometimes is necessary to reach certain parts of the level.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-10-26' FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/d8b/d8bfed2209bf96866506cca8022db5b7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Platformer') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Super Mario Odyssey') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Arcade') AS b ON CONFLICT DO NOTHING;

-- Game 10
INSERT INTO games(title, cover, description) VALUES('OKAMI HD / 大神 絶景版', 'https://media.rawg.io/media/games/a38/a3857b2445c70ac5dbe73b210a827ad8.jpg', 'Okami HD is a remaster of the original Ōkami released for PS2 and Wii in 2006. While the original game has only visited PS2 and Wii, the HD Remaster is playable on all the current generation consoles. While the original game has only visited PS2 and Wii, the HD Remaster is playable on all the current generation consoles. The updated version differs from the original in texture quality, HD does not feature some songs and include trophies. The whole narrative in the game circles around Japanese stylistics: folklore tales, agitated myths, and well-known country legends mix up in the game''s storytelling. The title also features unique stylistics inspired by Japanese ink-wash painting called Sumi-e. All of the game''s visuals are rendered via cel-shading. The game tells a story of Ōkami Amaterasu — the wolf representing the Japanese goddess of the sun. At the beginning of the game, she is going out for an adventure to seal the Orochi — demon who was unleashed by Susano, the great warrior. The game presents itself as a mix of puzzle and platformer. Throughout the game, the player follows the main story. However, the side quest is also available. Apart from the exploring sections, the protagonist also participates in multiple battles. The main weapon-style used in battles is brushing, which is used for the wide variety of the actions including wielding the weapon.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-12-12' FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Capcom', 'https://media.rawg.io/media/games/89a/89ac2742fcfeba3b95ac94457af766ef.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Capcom') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Capcom', 'https://media.rawg.io/media/games/9fb/9fbf956a16249def7625ab5dc3d09515.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Capcom') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 3') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Adventure') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'OKAMI HD / 大神 絶景版') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 11
INSERT INTO games(title, cover, description) VALUES('A Hat in Time', 'https://media.rawg.io/media/games/594/5949baae74fe9e399adbce0c44e28783.jpg', 'A Hat in Time is a cute-as-heck 3D platformer featuring a little girl who stitches hats for wicked powers.A little girl and her spaceshipIn A Hat in Time you play as a tiny space-travelling girl with a big tophat. Her adventure is halted when all her fuel, the Time Pieces, is lost and scattered across a nearby planet. Hat Kid must now jump, fight and stitch new hats to make her way into every nook and cranny of this new world in order to restore her fuel and resume her journey. On her way, she''ll bump into the menacing Mafia of Cooks, the goofy birds of Dead Bird Studio, the spooky shadows of Subcon Forest, and more!Murder on a train! Parades! Trespassing in a movie studio?Every mission in A Hat in Time is unique! At one moment you''ll be solving the Murder on the Owl Express by finding clues and interrogating the locals, the next moment you''ll be the band marshal in The Big Parade, or sneaking through the bird-run Dead Bird Studio!Small child, giant worldsJump freely around in 5 massive worlds with new adventures to discover around every corner! Just like any child, Hat Kid loves to climb and explore, no mountain is too big for her sense of adventure. She can do multiple jump moves, as well as climb walls, and swing over gaps!Cute hats, magical yarn and snappy badgesBy finding and collecting rare magical yarn, Hat Kid can stitch new cute hats with a variety of abilities, including a witch hat that allows her to cook explosive concoctions, and a wooden ghost mask that allows her to peek into other dimensions. Hats can become even more powerful, by attaching badges that are found, sold and traded by the locals!Community-funded, community-focusedA Hat in Time was successfully funded on Kickstarter, reaching nearly 10 times its goal! In order to celebrate our community, A Hat in Time is releasing with full modding and Steam Workshop support, an in-game screenshot mode, and more!') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-10-04' FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Gears for Breakfast', 'https://media.rawg.io/media/games/594/5949baae74fe9e399adbce0c44e28783.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Gears for Breakfast') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Humble Bundle', 'https://media.rawg.io/media/screenshots/609/60948085c9e410562947b3d8be2dfbb1.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Humble Bundle') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Gears for Breakfast', 'https://media.rawg.io/media/games/594/5949baae74fe9e399adbce0c44e28783.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Gears for Breakfast') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Humble Bundle, Inc.', 'https://media.rawg.io/media/games/9db/9db4eeb53c38611bfc94ff39bfc0feff.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Humble Bundle, Inc.') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'macOS') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 3') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Indie') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'A Hat in Time') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 12
INSERT INTO games(title, cover, description) VALUES('Sonic Forces', 'https://media.rawg.io/media/games/0e9/0e9d75008321d640e4a14a8b5e322620.jpg', 'In SONIC FORCES, the evil Dr. Eggman has conquered much of the world with help from a powerful and mysterious new villain named Infinite. Now, you must assist Sonic and build an army to reclaim the world as they fight against chaos and destruction. Defeat enemies with blazing speed as Modern Sonic, catapult past perilous platforms as Classic Sonic, and create your very own Custom Hero Character equipped with a variety of powerful gadgets. Experience fast-paced action with these three unique gameplay styles, explore iconic stages, plus, fight across unique added content with Shadow as a playable character! The fate of Sonic the Hedgehog’s world is in your hands – Join the Uprising.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-11-01' FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('SEGA', 'https://media.rawg.io/media/screenshots/8c4/8c414d6590b8c70b1cd374ce1a447f52.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'SEGA') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Hardlight', 'https://media.rawg.io/media/screenshots/863/863e5ed323f3b339efa8172415c913b0.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Hardlight') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('SEGA', 'https://media.rawg.io/media/screenshots/3f1/3f1c417b405a86ed7d92b903e0fcfd0c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'SEGA') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Sonic Team', 'https://media.rawg.io/media/screenshots/3a6/3a66a199ed4c3907cb406b91bdcc57a2.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Sonic Team') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'iOS') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Android') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Arcade') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Casual') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Adventure') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Sonic Forces') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 13
INSERT INTO games(title, cover, description) VALUES('Xenoblade Chronicles 2', 'https://media.rawg.io/media/games/a9a/a9a6055569c986a04d066b310ea57ebb.jpg', 'As the giant beasts march toward death, the last hope is a scavenger named Rex — and Pyra, a living weapon known as a Blade. Can you find the fabled paradise she calls home? Command a group of Blades and lead them to countless strategic victories before the world ends. Each Titan hosts its own distinct cultures, wildlife, and diverse regions to explore. Search the vast open areas and labyrinthine corridors for treasure, secret paths, and creatures to battle and index. During these escapades you''ll get to know a large cast of eclectic characters, including the weaponized life forms known as Blades. Gather these allies, bond with them to increase their power, and utilize their special ARTS to devastate enemies. But to save the world of Alrest, you must first demystify its cloudy past. A new story in the Xenoblade Chronicles™ series. The next adventure is on the Nintendo Switch™ console—set on the backs of colossal, living Titans. Discover each Titan’s diverse regions, culture, wildlife, equipment, and hidden secrets Find, bond with, and command weaponized life forms known as Blades to earn abilities and enhance them Uncover the history of Alrest and the mystery of its endless ocean of clouds') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2017-11-30' FROM (SELECT game FROM games WHERE title LIKE 'Xenoblade Chronicles 2') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Xenoblade Chronicles 2') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Monolith Soft', 'https://media.rawg.io/media/screenshots/c7b/c7b9db51a98e74a63cac67b932652a46.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Xenoblade Chronicles 2') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Monolith Soft') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Xenoblade Chronicles 2') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Xenoblade Chronicles 2') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 14
INSERT INTO games(title, cover, description) VALUES('Wolfenstein: Youngblood', 'https://media.rawg.io/media/games/c64/c64d2f63cabeab9126693b7d39539c8d.jpg', 'Wolfenstein: Youngblood is a spin-off installment of the Wolfenstein series. It fills the gap between Wolfenstein II: The New Colossus and the upcoming Wolfenstein 3. Like its predecessors, Wolfenstein: Youngblood is set in an alternate reality, in which Nazi Germany won World War II by using anachronistically developed tech. The Third Reich managed to conquer Europe and North America. The spin-off is set in an alternate 1980. Nineteen years have passed since the events of Wolfenstein II: The New Colossus, which are now known as the Second American Revolution. The US is now free from German occupation, but the battle continues as Nazi still control most of Europe. The game''s main protagonists are Jessica and Sophia, the twin sisters and daughters of the Wolfenstein series'' trademark protagonist, war veteran B.J. Blazkowicz. Their father trained them as fighters and shooters, and as they reached adulthood, they joined the Global Resistance to fight against the Nazis. When Blazkowicz goes missing on a secret mission in the Vichy France, the twins set out to search him in the Nazi-occupied Paris. They also assist the French Resistance in fighting the occupants. The game allows two players to cooperate online by controlling two sisters at once as they walk through the story campaign.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2019-07-26' FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/c4b/c4b0cab189e73432de3a250d8cf1c84e.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Arkane Studios', 'https://media.rawg.io/media/games/eb0/eb0978fb3cbc682ed9cdae2030ee17b8.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Arkane Studios') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/55c/55c7e7a972d361db3677c1dd10a5558d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Machine Games', 'https://media.rawg.io/media/games/c64/c64d2f63cabeab9126693b7d39539c8d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Machine Games') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Shooter') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Wolfenstein: Youngblood') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 15
INSERT INTO games(title, cover, description) VALUES('Dragon Quest Builders 2', 'https://media.rawg.io/media/games/0b6/0b6215a334d09c36ce3a43ad60f493ee.jpg', 'DRAGON QUEST BUILDERS 2 is the critically acclaimed block-building RPG from DRAGON QUEST series creators Yuji Horii, character designer Akira Toriyama and composer Koichi Sugiyama – now for Steam players!</p>
<p>The Steam version includes all the Season Pass content previously released on console versions: Hotto Stuff Pack, Modernist Pack, Aquarium Pack, Designer’s Sunglasses, Legendary Builder Outfit, Dragonlord’s Throne, and more!</p>
<p>Don’t let the name fool you, despite the 2, this is a completely standalone experience featuring new characters, an expansive world, unlimited building combinations, and a storyline that’s sure to satisfy long-time fans and newcomers alike!</p>
<p>Embark on an epic journey and became the master Builder! Customized your character and set off to revive a forsaken world alongside a mysterious companion named Malroth. Then, take your builder online and join your friends to collaborate and create something truly magnificent.</p>
<p>The evil Children of Hargon are determined to eradicate all creators and have outlawed the building, cooking, and creation of all things. To spread their destructive dogma, the calamitous cult captures the builders of the world. All hope seems to be lost until you, a young apprentice builder, manage to escape from the clutches of evil.</p>
<p>After washing up on the shores of the deserted Isle of Awakening, you encounter the spirited Malroth, a mysterious youth with no memory of his past. With the help of your fearless new friend, you embark on a grand adventure to gather the skills required to become a full-fledged builder, but the road you build is paved with peril. Only you can defeat the Children of Hargon, uncover the secrets of Malroth’s past, and unravel the riddles of this mysterious land.</p>
<li>Block-building RPG – Prove yourself as a Builder and a Warrior, help the people of the realm to rebuild their destroyed lands. The more you help the more you’ll receive hearts and recognition. Prepare for a cure of creativity and friendliness!</li>
<li>Creative open-world – Construct big structures in this fantasy block world with a large variety of options.</li>
<li>Explore, gather, and craft – Each island contains its own set of unique materials to help you grow, craft, and cook new creations. Along the way you’ll improve your skills and grow as a builder as you learn new recipes and blueprints.</li>
<li>Battle fearsome foes alongside your partner – Accompanying you on your quest is the mysterious Malroth, an aggressive amnesiac with a fondness for fighting foes. His powerful attacks and skills on the battlefield are truly indispensable!</li>
<li>Dash, swim, and glide across an expansive world – Run across open fields and explore charming villages, treacherous mines, and spectacular castles. Dive into the watery depths to discover hidden treasures, climb the highest mountain to catch the sunset, and glide home to rest up for your next day of adventure.</li>
<li>Plant, water, and grow! – Work together with your villagers to till soil, plants seeds, and raise a multitude of crops. Be sure to customize the way you build your fields to support the kind of crops you’re growing. Harvest anything from the humble cabbage to sweet sugar canes!</li>
<li>Design and Build with Friends Online – Big projects require big help! Up to 4 players can team up online to build anything you can imagine on the sandbox Isle of Awakening.</li>') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2019-07-12' FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Square Enix', 'https://media.rawg.io/media/games/81e/81e6c6819d4322caf375b6735c3043ec.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Square Enix') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Square Enix', 'https://media.rawg.io/media/games/683/6833fbb183fd72a61c032501e3bc6d36.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Square Enix') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Koei Tecmo', 'https://media.rawg.io/media/screenshots/4bf/4bfb7439560f10522bfa3186944b5b00.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Koei Tecmo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Adventure') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Dragon Quest Builders 2') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 16
INSERT INTO games(title, cover, description) VALUES('Marvel Ultimate Alliance 3: The Black Order', 'https://media.rawg.io/media/games/e25/e25a62b6ee40c948c55c09ff2802ff2e.jpg', 'Assemble your ultimate team of Marvel Super Heroes from a huge cast including the Avengers, the Guardians of the Galaxy, the X-Men, and more! Team up with friends to prevent galactic devastation at the hands of the mad cosmic tyrant Thanos and his ruthless warmasters, The Black Order.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2019-07-19' FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Team NINJA', 'https://media.rawg.io/media/games/590/59030a090559161f2c1f4ac7182d3be1.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Team NINJA') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Koei Tecmo', 'https://media.rawg.io/media/screenshots/4bf/4bfb7439560f10522bfa3186944b5b00.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Koei Tecmo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Marvel Ultimate Alliance 3: The Black Order') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 17
INSERT INTO games(title, cover, description) VALUES('Fire Emblem: Three Houses', 'https://media.rawg.io/media/games/530/53081dbd5003f990fa5312404ac3d71a.jpg', 'Fire Emblem: Three Houses is a RPG-strategy game developed by Intelligent Systems. It came out on 26-07-2019. Nintendo published the game. Most rawgers rated the game as "Exceptional". Fire Emblem: Three Houses is available on Nintendo Switch. The game is sold via Nintendo eShop. It was scored by Masato Kouda and Rei Kondoh.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2019-07-26' FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Nintendo', 'https://media.rawg.io/media/games/e23/e2345c839b323a94b6811705fda5af73.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Nintendo') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Intelligent Systems', 'https://media.rawg.io/media/screenshots/4c7/4c7346d0d4a07dcad8eb14f683f72cbc.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Intelligent Systems') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Strategy') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Fire Emblem: Three Houses') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 18
INSERT INTO games(title, cover, description) VALUES('DOOM Eternal', 'https://media.rawg.io/media/games/3ea/3ea3c9bbd940b6cb7f2139e42d3d443f.jpg', 'As the DOOM Slayer, you return to find Earth has suffered a demonic invasion. Raze Hell and discover the Slayer’s origins and his enduring mission to rip and tear…until it is done. Experience the ultimate combination of speed and power as you battle your way across dimensions with the next leap in push-forward, first-person combat. Armed with a shoulder-mounted flamethrower, retractable wrist-mounted blade, upgraded guns and mods, and abilities like the Double Dash, you''re faster, stronger, and more versatile than ever. Take what you need from your enemies: Glory kill for extra health, incinerate for armor, and chainsaw demons to stock up on ammo to become the ultimate demon-slayer. BATTLEMODE is the new 2 versus 1 multiplayer experience built from the ground up at id Software. A fully-armed DOOM Slayer faces off against two player-controlled demons, duking it in a best-of-five round match of intense first-person combat. BATTLEMODE launches with 6 handcrafted maps and 5 playable demons – the Marauder, Archvile, Revenant, Mancubus and Pain Elemental.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2020-03-20' FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/c4b/c4b0cab189e73432de3a250d8cf1c84e.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Bethesda Softworks', 'https://media.rawg.io/media/games/55c/55c7e7a972d361db3677c1dd10a5558d.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Bethesda Softworks') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('id Software', 'https://media.rawg.io/media/games/38a/38af969459ad6e5de116ec8a4a84218c.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'id Software') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PC') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Xbox One') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Shooter') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'DOOM Eternal') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;

-- Game 19
INSERT INTO games(title, cover, description) VALUES('Persona 5 Scramble: The Phantom Strikers', 'https://media.rawg.io/media/games/2d5/2d55bd544440c85116bd9239279eb021.jpg', 'The Phantom Thieves meet up again during summer vacation and get caught up in another incident. Mysterious case starts happening all over Japan, and Palaces the cognitive world of twisted adults have returned. The Phantom Thieves jump back into action to work towards solving the case.') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2020-02-20' FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO publishers(publisher_name, publisher_logo) VALUES('Atlus', 'https://media.rawg.io/media/games/676/676482d81d0eccc767df49a43a1189f9.jpg') ON CONFLICT DO NOTHING;
INSERT INTO publishing(game, publisher) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT publisher FROM publishers WHERE publisher_name LIKE 'Atlus') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Omega Force', 'https://media.rawg.io/media/screenshots/c93/c93b6722c7dcf1ac6d237c1fd3ae3847.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Omega Force') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Koei Tecmo', 'https://media.rawg.io/media/screenshots/4bf/4bfb7439560f10522bfa3186944b5b00.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Koei Tecmo') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'PlayStation 4') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'Action') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Persona 5 Scramble: The Phantom Strikers') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;

-- Game 20
INSERT INTO games(title, cover, description) VALUES('Tokyo Mirage Sessions ♯FE Encore', 'https://media.rawg.io/media/games/911/9116aa161959b26d738a1414a3a110af.jpg', 'The game that brought together the worlds of Fire Emblem and ATLUS is coming to Nintendo Switch. Tokyo Mirage Sessions ♯FE Encore is the Nintendo Switch version of the acclaimed RPG that originally launched on Wii U. This new version of the game contains a new song that wasn’t in the original, new story elements and the ability to take it on the go!') ON CONFLICT DO NOTHING;
INSERT INTO releases(game, region, release_date) SELECT game, region, '2020-01-17' FROM (SELECT game FROM games WHERE title LIKE 'Tokyo Mirage Sessions ♯FE Encore') AS a, (SELECT region FROM regions WHERE region_name LIKE 'Worldwide') AS b ON CONFLICT DO NOTHING;
INSERT INTO developers(developer_name, developer_logo) VALUES('Atlus', 'https://media.rawg.io/media/games/980/980086d012c5a27cb44010d4204578a1.jpg') ON CONFLICT DO NOTHING;
INSERT INTO development(game, developer) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Tokyo Mirage Sessions ♯FE Encore') AS a, (SELECT developer FROM developers WHERE developer_name LIKE 'Atlus') AS b ON CONFLICT DO NOTHING;
INSERT INTO game_versions(game, platform) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Tokyo Mirage Sessions ♯FE Encore') AS a, (SELECT platform FROM platforms WHERE platform_name LIKE 'Nintendo Switch') AS b ON CONFLICT DO NOTHING;
INSERT INTO classifications(game, genre) SELECT * FROM (SELECT game FROM games WHERE title LIKE 'Tokyo Mirage Sessions ♯FE Encore') AS a, (SELECT genre FROM genres WHERE genre_name LIKE 'RPG') AS b ON CONFLICT DO NOTHING;